site_name: OctaveTutorial
pages:
- "<span class='fa fa-home'></span> Home": "index.md"
- "<span class='fa fa-book'></span> Learn":
  - "Matrix": 'matrix.md'

markdown_extensions:
    - footnotes
